### ISSUE TITLE
コーディングで意識していること

### ISSUE THREAD

**Issue by irohasu-lab** [irohasu-lab/kanban#40]
* 機能単位でプロシージャを作る。
* 型を指定する、暗黙の型となるようにしない。
* スコープを明示的にする。（public と private）
* マジックナンバーを使わない。
* ByVal、値渡しの思想でコードを書く。値の上書きはしない。Function で結果となる値をもらう様にする。
* 値渡しと参照渡しを明示的にする。
* 横に長い記述にならないように ` _` を活用して改行する。（上限がある。）
* IF文のネストが深くならないようにする。
* チェック系処理のプロシージャはチェックだけする様にして、結果に対するメッセージはチェックプロシージャを呼ぶ側で設定する。
* どの WorkBook の Sheets に対する参照なのか明示的にする。

**Comment by ichinohe-r** [comment]
* 最小単位でチェックする
* チェックの順番
     * 1. インパラチェック
     * 2. パラメータの内容チェック
